/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ApiWireRouteImport } from './routes/api.wire'
import { Route as ApiWitnessRouteImport } from './routes/api.witness'
import { Route as IIdRouteImport } from './routes/i.$id'
import { Route as ApiOgIdRouteImport } from './routes/api.og.$id'
import { Route as ApiPublicLiveRouteImport } from './routes/api.public.live'
import { Route as ApiPushStatusRouteImport } from './routes/api.push.status'
import { Route as ApiPushSubscribeRouteImport } from './routes/api.push.subscribe'
import { Route as ApiPushTestRouteImport } from './routes/api.push.test'
import { Route as ApiPushUnsubscribeRouteImport } from './routes/api.push.unsubscribe'
import { Route as ApiSuperfeedrSubscribeRouteImport } from './routes/api.superfeedr.subscribe'
import { Route as ApiSuperfeedrWebhookRouteImport } from './routes/api.superfeedr.webhook'
import { Route as ApiPublicLiveRssRouteImport } from './routes/api.public.live.rss'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWireRoute = ApiWireRouteImport.update({
  id: '/api/wire',
  path: '/api/wire',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWitnessRoute = ApiWitnessRouteImport.update({
  id: '/api/witness',
  path: '/api/witness',
  getParentRoute: () => rootRouteImport,
} as any)
const IIdRoute = IIdRouteImport.update({
  id: '/i/$id',
  path: '/i/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveRoute = ApiPublicLiveRouteImport.update({
  id: '/api/public/live',
  path: '/api/public/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushStatusRoute = ApiPushStatusRouteImport.update({
  id: '/api/push/status',
  path: '/api/push/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushTestRoute = ApiPushTestRouteImport.update({
  id: '/api/push/test',
  path: '/api/push/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushUnsubscribeRoute = ApiPushUnsubscribeRouteImport.update({
  id: '/api/push/unsubscribe',
  path: '/api/push/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuperfeedrSubscribeRoute = ApiSuperfeedrSubscribeRouteImport.update({
  id: '/api/superfeedr/subscribe',
  path: '/api/superfeedr/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuperfeedrWebhookRoute = ApiSuperfeedrWebhookRouteImport.update({
  id: '/api/superfeedr/webhook',
  path: '/api/superfeedr/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveRssRoute = ApiPublicLiveRssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => ApiPublicLiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ready': typeof ReadyRoute
  '/api/wire': typeof ApiWireRoute
  '/api/witness': typeof ApiWitnessRoute
  '/i/$id': typeof IIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/public/live': typeof ApiPublicLiveRouteWithChildren
  '/api/push/status': typeof ApiPushStatusRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/superfeedr/subscribe': typeof ApiSuperfeedrSubscribeRoute
  '/api/superfeedr/webhook': typeof ApiSuperfeedrWebhookRoute
  '/api/public/live/rss': typeof ApiPublicLiveRssRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ready': typeof ReadyRoute
  '/api/wire': typeof ApiWireRoute
  '/api/witness': typeof ApiWitnessRoute
  '/i/$id': typeof IIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/public/live': typeof ApiPublicLiveRouteWithChildren
  '/api/push/status': typeof ApiPushStatusRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/superfeedr/subscribe': typeof ApiSuperfeedrSubscribeRoute
  '/api/superfeedr/webhook': typeof ApiSuperfeedrWebhookRoute
  '/api/public/live/rss': typeof ApiPublicLiveRssRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ready': typeof ReadyRoute
  '/api/wire': typeof ApiWireRoute
  '/api/witness': typeof ApiWitnessRoute
  '/i/$id': typeof IIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/public/live': typeof ApiPublicLiveRouteWithChildren
  '/api/push/status': typeof ApiPushStatusRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/test': typeof ApiPushTestRoute
  '/api/push/unsubscribe': typeof ApiPushUnsubscribeRoute
  '/api/superfeedr/subscribe': typeof ApiSuperfeedrSubscribeRoute
  '/api/superfeedr/webhook': typeof ApiSuperfeedrWebhookRoute
  '/api/public/live/rss': typeof ApiPublicLiveRssRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ready'
    | '/api/wire'
    | '/api/witness'
    | '/i/$id'
    | '/api/og/$id'
    | '/api/public/live'
    | '/api/push/status'
    | '/api/push/subscribe'
    | '/api/push/test'
    | '/api/push/unsubscribe'
    | '/api/superfeedr/subscribe'
    | '/api/superfeedr/webhook'
    | '/api/public/live/rss'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ready'
    | '/api/wire'
    | '/api/witness'
    | '/i/$id'
    | '/api/og/$id'
    | '/api/public/live'
    | '/api/push/status'
    | '/api/push/subscribe'
    | '/api/push/test'
    | '/api/push/unsubscribe'
    | '/api/superfeedr/subscribe'
    | '/api/superfeedr/webhook'
    | '/api/public/live/rss'
  id:
    | '__root__'
    | '/'
    | '/ready'
    | '/api/wire'
    | '/api/witness'
    | '/i/$id'
    | '/api/og/$id'
    | '/api/public/live'
    | '/api/push/status'
    | '/api/push/subscribe'
    | '/api/push/test'
    | '/api/push/unsubscribe'
    | '/api/superfeedr/subscribe'
    | '/api/superfeedr/webhook'
    | '/api/public/live/rss'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadyRoute: typeof ReadyRoute
  ApiWireRoute: typeof ApiWireRoute
  ApiWitnessRoute: typeof ApiWitnessRoute
  IIdRoute: typeof IIdRoute
  ApiOgIdRoute: typeof ApiOgIdRoute
  ApiPublicLiveRoute: typeof ApiPublicLiveRouteWithChildren
  ApiPushStatusRoute: typeof ApiPushStatusRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushTestRoute: typeof ApiPushTestRoute
  ApiPushUnsubscribeRoute: typeof ApiPushUnsubscribeRoute
  ApiSuperfeedrSubscribeRoute: typeof ApiSuperfeedrSubscribeRoute
  ApiSuperfeedrWebhookRoute: typeof ApiSuperfeedrWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wire': {
      id: '/api/wire'
      path: '/api/wire'
      fullPath: '/api/wire'
      preLoaderRoute: typeof ApiWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/witness': {
      id: '/api/witness'
      path: '/api/witness'
      fullPath: '/api/witness'
      preLoaderRoute: typeof ApiWitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$id': {
      id: '/i/$id'
      path: '/i/$id'
      fullPath: '/i/$id'
      preLoaderRoute: typeof IIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live': {
      id: '/api/public/live'
      path: '/api/public/live'
      fullPath: '/api/public/live'
      preLoaderRoute: typeof ApiPublicLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/status': {
      id: '/api/push/status'
      path: '/api/push/status'
      fullPath: '/api/push/status'
      preLoaderRoute: typeof ApiPushStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/test': {
      id: '/api/push/test'
      path: '/api/push/test'
      fullPath: '/api/push/test'
      preLoaderRoute: typeof ApiPushTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/unsubscribe': {
      id: '/api/push/unsubscribe'
      path: '/api/push/unsubscribe'
      fullPath: '/api/push/unsubscribe'
      preLoaderRoute: typeof ApiPushUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/superfeedr/subscribe': {
      id: '/api/superfeedr/subscribe'
      path: '/api/superfeedr/subscribe'
      fullPath: '/api/superfeedr/subscribe'
      preLoaderRoute: typeof ApiSuperfeedrSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/superfeedr/webhook': {
      id: '/api/superfeedr/webhook'
      path: '/api/superfeedr/webhook'
      fullPath: '/api/superfeedr/webhook'
      preLoaderRoute: typeof ApiSuperfeedrWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live/rss': {
      id: '/api/public/live/rss'
      path: '/rss'
      fullPath: '/api/public/live/rss'
      preLoaderRoute: typeof ApiPublicLiveRssRouteImport
      parentRoute: typeof ApiPublicLiveRoute
    }
  }
}

interface ApiPublicLiveRouteChildren {
  ApiPublicLiveRssRoute: typeof ApiPublicLiveRssRoute
}

const ApiPublicLiveRouteChildren: ApiPublicLiveRouteChildren = {
  ApiPublicLiveRssRoute: ApiPublicLiveRssRoute,
}

const ApiPublicLiveRouteWithChildren = ApiPublicLiveRoute._addFileChildren(
  ApiPublicLiveRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadyRoute: ReadyRoute,
  ApiWireRoute: ApiWireRoute,
  ApiWitnessRoute: ApiWitnessRoute,
  IIdRoute: IIdRoute,
  ApiOgIdRoute: ApiOgIdRoute,
  ApiPublicLiveRoute: ApiPublicLiveRouteWithChildren,
  ApiPushStatusRoute: ApiPushStatusRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushTestRoute: ApiPushTestRoute,
  ApiPushUnsubscribeRoute: ApiPushUnsubscribeRoute,
  ApiSuperfeedrSubscribeRoute: ApiSuperfeedrSubscribeRoute,
  ApiSuperfeedrWebhookRoute: ApiSuperfeedrWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
