/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as ApiWireRouteImport } from './routes/api.wire'
import { Route as IIdRouteImport } from './routes/i.$id'
import { Route as ApiOgIdRouteImport } from './routes/api.og.$id'
import { Route as ApiSuperfeedrSubscribeRouteImport } from './routes/api.superfeedr.subscribe'
import { Route as ApiSuperfeedrWebhookRouteImport } from './routes/api.superfeedr.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWireRoute = ApiWireRouteImport.update({
  id: '/api/wire',
  path: '/api/wire',
  getParentRoute: () => rootRouteImport,
} as any)
const IIdRoute = IIdRouteImport.update({
  id: '/i/$id',
  path: '/i/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIdRoute = ApiOgIdRouteImport.update({
  id: '/api/og/$id',
  path: '/api/og/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuperfeedrSubscribeRoute = ApiSuperfeedrSubscribeRouteImport.update({
  id: '/api/superfeedr/subscribe',
  path: '/api/superfeedr/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuperfeedrWebhookRoute = ApiSuperfeedrWebhookRouteImport.update({
  id: '/api/superfeedr/webhook',
  path: '/api/superfeedr/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ready': typeof ReadyRoute
  '/api/wire': typeof ApiWireRoute
  '/i/$id': typeof IIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/superfeedr/subscribe': typeof ApiSuperfeedrSubscribeRoute
  '/api/superfeedr/webhook': typeof ApiSuperfeedrWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ready': typeof ReadyRoute
  '/api/wire': typeof ApiWireRoute
  '/i/$id': typeof IIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/superfeedr/subscribe': typeof ApiSuperfeedrSubscribeRoute
  '/api/superfeedr/webhook': typeof ApiSuperfeedrWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ready': typeof ReadyRoute
  '/api/wire': typeof ApiWireRoute
  '/i/$id': typeof IIdRoute
  '/api/og/$id': typeof ApiOgIdRoute
  '/api/superfeedr/subscribe': typeof ApiSuperfeedrSubscribeRoute
  '/api/superfeedr/webhook': typeof ApiSuperfeedrWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ready'
    | '/api/wire'
    | '/i/$id'
    | '/api/og/$id'
    | '/api/superfeedr/subscribe'
    | '/api/superfeedr/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ready'
    | '/api/wire'
    | '/i/$id'
    | '/api/og/$id'
    | '/api/superfeedr/subscribe'
    | '/api/superfeedr/webhook'
  id:
    | '__root__'
    | '/'
    | '/ready'
    | '/api/wire'
    | '/i/$id'
    | '/api/og/$id'
    | '/api/superfeedr/subscribe'
    | '/api/superfeedr/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadyRoute: typeof ReadyRoute
  ApiWireRoute: typeof ApiWireRoute
  IIdRoute: typeof IIdRoute
  ApiOgIdRoute: typeof ApiOgIdRoute
  ApiSuperfeedrSubscribeRoute: typeof ApiSuperfeedrSubscribeRoute
  ApiSuperfeedrWebhookRoute: typeof ApiSuperfeedrWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wire': {
      id: '/api/wire'
      path: '/api/wire'
      fullPath: '/api/wire'
      preLoaderRoute: typeof ApiWireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i/$id': {
      id: '/i/$id'
      path: '/i/$id'
      fullPath: '/i/$id'
      preLoaderRoute: typeof IIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$id': {
      id: '/api/og/$id'
      path: '/api/og/$id'
      fullPath: '/api/og/$id'
      preLoaderRoute: typeof ApiOgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/superfeedr/subscribe': {
      id: '/api/superfeedr/subscribe'
      path: '/api/superfeedr/subscribe'
      fullPath: '/api/superfeedr/subscribe'
      preLoaderRoute: typeof ApiSuperfeedrSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/superfeedr/webhook': {
      id: '/api/superfeedr/webhook'
      path: '/api/superfeedr/webhook'
      fullPath: '/api/superfeedr/webhook'
      preLoaderRoute: typeof ApiSuperfeedrWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadyRoute: ReadyRoute,
  ApiWireRoute: ApiWireRoute,
  IIdRoute: IIdRoute,
  ApiOgIdRoute: ApiOgIdRoute,
  ApiSuperfeedrSubscribeRoute: ApiSuperfeedrSubscribeRoute,
  ApiSuperfeedrWebhookRoute: ApiSuperfeedrWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
